# Generated by Django 4.2.24 on 2025-11-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsnapshot',
            options={'get_latest_by': 'asof_ts', 'ordering': ['-asof_ts']},
        ),
    ]
