# Generated by Django 4.2.24 on 2025-09-19 22:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ibkr_exec_id', models.CharField(max_length=64, unique=True)),
                ('fill_ts', models.DateTimeField()),
                ('qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('venue', models.CharField(blank=True, default='', max_length=64)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='IbkrContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('con_id', models.BigIntegerField(unique=True)),
                ('sec_type', models.CharField(max_length=16)),
                ('exchange', models.CharField(blank=True, default='', max_length=32)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('local_symbol', models.CharField(blank=True, default='', max_length=64)),
                ('last_trade_date_or_contract_month', models.CharField(blank=True, default='', max_length=16)),
                ('strike', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('right', models.CharField(blank=True, default='', max_length=1)),
                ('multiplier', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('exchange', models.CharField(blank=True, default='', max_length=32)),
                ('asset_type', models.CharField(choices=[('equity', 'Equity'), ('etf', 'ETF'), ('option', 'Option'), ('future', 'Future'), ('crypto', 'Crypto'), ('fx', 'FX')], max_length=16)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('base_currency', models.CharField(default='USD', max_length=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('broker_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='accounts.brokeraccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('avg_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('market_price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('market_value', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('asof_ts', models.DateTimeField()),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.brokeraccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.client')),
                ('ibkr_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='portfolio.ibkrcontract')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='portfolio.instrument')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ibkr_order_id', models.BigIntegerField()),
                ('parent_ibkr_order_id', models.BigIntegerField(blank=True, null=True)),
                ('side', models.CharField(max_length=4)),
                ('order_type', models.CharField(max_length=8)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('aux_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('tif', models.CharField(blank=True, default='', max_length=8)),
                ('status', models.CharField(default='Unknown', max_length=32)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_ts', models.DateTimeField()),
                ('updated_ts', models.DateTimeField()),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.brokeraccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.client')),
                ('ibkr_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='portfolio.ibkrcontract')),
            ],
        ),
        migrations.CreateModel(
            name='OptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('assignment', 'Assignment'), ('exercise', 'Exercise'), ('expiration', 'Expiration')], max_length=16)),
                ('event_ts', models.DateTimeField()),
                ('qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_events', to='accounts.brokeraccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_events', to='accounts.client')),
                ('ibkr_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option_events', to='portfolio.ibkrcontract')),
            ],
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['symbol', 'asset_type'], name='portfolio_i_symbol_ea15a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together={('symbol', 'exchange', 'asset_type', 'currency')},
        ),
        migrations.AddField(
            model_name='ibkrcontract',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ibkr_contracts', to='portfolio.instrument'),
        ),
        migrations.AddField(
            model_name='execution',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='execution',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='portfolio.order'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['client', 'broker_account', 'asof_ts'], name='portfolio_p_client__1e1ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['client', 'portfolio', 'instrument'], name='portfolio_p_client__5ddd9b_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['client', 'asof_ts'], name='portfolio_p_client__153da3_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['client', 'name'], name='portfolio_p_client__3c6902_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['client'], name='portfolio_p_client__cfab0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('client', 'name')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'broker_account'], name='portfolio_o_client__c11eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'created_ts'], name='portfolio_o_client__921c9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('broker_account', 'ibkr_order_id')},
        ),
        migrations.AddIndex(
            model_name='optionevent',
            index=models.Index(fields=['client', 'event_ts'], name='portfolio_o_client__218194_idx'),
        ),
        migrations.AddIndex(
            model_name='optionevent',
            index=models.Index(fields=['client', 'event_type'], name='portfolio_o_client__2fea78_idx'),
        ),
        migrations.AddIndex(
            model_name='ibkrcontract',
            index=models.Index(fields=['con_id'], name='portfolio_i_con_id_d237cc_idx'),
        ),
        migrations.AddIndex(
            model_name='ibkrcontract',
            index=models.Index(fields=['instrument'], name='portfolio_i_instrum_8dec62_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['client', 'fill_ts'], name='portfolio_e_client__37029a_idx'),
        ),
    ]
