# Generated by Django 4.2.24 on 2025-11-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_portfolio_p_client__3c6902_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'get_latest_by': 'asof_ts', 'ordering': ['-asof_ts']},
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('broker_account', 'instrument', 'asof_ts'), name='uniq_position_ba_instr_asof'),
        ),
    ]
