# Generated by Django 4.2.24 on 2025-09-19 22:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('IBKR', 'IBKR Live'), ('IBKR-PAPER', 'IBKR Paper (via IBKR)'), ('SIM', 'Simulated (local)')], default='IBKR', max_length=16)),
                ('account_code', models.CharField(blank=True, default='', max_length=64)),
                ('base_currency', models.CharField(default='USD', max_length=8)),
                ('nickname', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_accounts', to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asof_ts', models.DateTimeField()),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('cash', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('buying_power', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('maintenance_margin', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('used_margin', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='accounts.brokeraccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_snapshots', to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('trader', 'Trader'), ('viewer', 'Viewer')], default='viewer', max_length=16)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'user'], name='accounts_cl_client__e2931d_idx'), models.Index(fields=['user'], name='accounts_cl_user_id_0f1c83_idx')],
                'unique_together': {('client', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='brokeraccount',
            index=models.Index(fields=['client', 'kind'], name='accounts_br_client__35f714_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeraccount',
            index=models.Index(fields=['client', 'account_code'], name='accounts_br_client__c6c52c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brokeraccount',
            unique_together={('client', 'kind', 'account_code')},
        ),
        migrations.AddIndex(
            model_name='accountsnapshot',
            index=models.Index(fields=['client', 'broker_account', 'asof_ts'], name='accounts_ac_client__5fc4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsnapshot',
            index=models.Index(fields=['broker_account', 'asof_ts'], name='accounts_ac_broker__d28020_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountsnapshot',
            constraint=models.UniqueConstraint(fields=('broker_account', 'asof_ts'), name='uniq_broker_asof'),
        ),
    ]
