# Generated by Django 4.2.24 on 2025-10-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='portfolio',
            name='portfolio_p_client__3c6902_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='portfolio_p_client__cfab0d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['client', 'broker_account'], name='idx_portfolio_client_ba'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['broker_account', 'name'], name='idx_portfolio_ba_name'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('client', 'broker_account', 'name'), name='uniq_portfolio_client_ba_name'),
        ),
    ]
