# Generated by Django 4.2.24 on 2025-09-19 22:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asof_ts', models.DateTimeField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('required_margin', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='accounts.client')),
                ('ibkr_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities_contract', to='portfolio.ibkrcontract')),
                ('underlier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities_underlier', to='portfolio.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategyInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, default='', max_length=256)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_instances', to='accounts.client')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_instances', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='v1', max_length=64)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('code_ref', models.CharField(blank=True, default='', max_length=256)),
                ('strategy_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='strategies.strategydefinition')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_ts', models.DateTimeField()),
                ('mode', models.CharField(choices=[('daily', 'Daily'), ('backtest', 'Backtest'), ('manual', 'Manual')], default='daily', max_length=16)),
                ('status', models.CharField(default='ok', max_length=32)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=dict)),
                ('strategy_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='strategies.strategyinstance')),
            ],
        ),
        migrations.AddField(
            model_name='strategyinstance',
            name='strategy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='strategies.strategyversion'),
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asof_ts', models.DateTimeField()),
                ('type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='accounts.client')),
                ('ibkr_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals_contract', to='portfolio.ibkrcontract')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='portfolio.portfolio')),
                ('strategy_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='strategies.strategyinstance')),
                ('underlier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals_underlier', to='portfolio.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asof_ts', models.DateTimeField()),
                ('action', models.CharField(max_length=64)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('rationale', models.TextField(blank=True, default='')),
                ('plan_id', models.UUIDField(blank=True, null=True)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='accounts.brokeraccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='accounts.client')),
                ('ibkr_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_contract', to='portfolio.ibkrcontract')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='strategies.opportunity')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='portfolio.portfolio')),
                ('strategy_instance', models.ForeignKey(default=Decimal('0'), on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='strategies.strategyinstance')),
                ('strategy_version', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='strategies.strategyversion')),
                ('underlier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations_underlier', to='portfolio.instrument')),
            ],
        ),
        migrations.AddIndex(
            model_name='strategyversion',
            index=models.Index(fields=['strategy_def', 'version'], name='strategies__strateg_0e314a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyversion',
            unique_together={('strategy_def', 'version')},
        ),
        migrations.AddIndex(
            model_name='strategyrun',
            index=models.Index(fields=['strategy_instance', 'run_ts'], name='strategies__strateg_f1d4e2_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyinstance',
            index=models.Index(fields=['client', 'portfolio'], name='strategies__client__c0bb87_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyinstance',
            index=models.Index(fields=['client', 'enabled'], name='strategies__client__e2498c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyinstance',
            unique_together={('client', 'name')},
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['client', 'asof_ts'], name='strategies__client__9227b9_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['client', 'type'], name='strategies__client__532a65_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['client', 'asof_ts'], name='strategies__client__3fdf28_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['client', 'portfolio', 'asof_ts'], name='strategies__client__9b7bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['client', 'action'], name='strategies__client__a81d12_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['plan_id'], name='strategies__plan_id_f72c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['opportunity'], name='strategies__opportu_620b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['client', 'asof_ts'], name='strategies__client__0fe5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['client'], name='strategies__client__3579cd_idx'),
        ),
    ]
