# Generated by Django 4.2.24 on 2025-12-03 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_position_options_and_more'),
        ('strategies', '0002_alter_recommendation_strategy_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='underlier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommendations_underlier', to='portfolio.instrument'),
        ),
    ]
