# Generated by Django 4.2.24 on 2025-12-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_alter_recommendation_underlier'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyrun',
            name='debug_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='strategyrun',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategyrun',
            name='error_trace',
            field=models.TextField(blank=True, default=''),
        ),
    ]
